// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

import site from './reference.config.json' with { type: 'json' };

/*
 * The Horizon Design System docs site.
 *
 * Storybook is where components render, every variant and state, live. This site
 * is where they are explained: when to use one, when not to, how to call it, what
 * it was built from. Component pages embed and link into Storybook rather than
 * re-rendering anything, so there is no second rendering to keep in step.
 *
 * The reference half (home, components, tokens, changelog, roadmap, news) is
 * generated by scripts/generate.mjs from the design system repo. The guides are
 * written from the same repo. See .claude/skills/astro-page/SKILL.md there.
 */
export default defineConfig({
  site: site.siteUrl,
  server: { port: Number(process.env.PORT) || 4321 },
  /*
   * Addresses this site served before it was regrouped. `Astro Link` in the
   * registry recorded the first two, so they must keep landing on the page.
   */
  redirects: {
    '/components': '/core/components/overview/',
    '/components/button': '/core/components/button/',
    '/components/card': '/core/components/card/',
  },
  integrations: [
    starlight({
      title: site.title,
      description: site.description,
      social: [{ icon: 'github', label: 'GitHub', href: site.repoUrl }],
      /*
       * Written out, not autogenerated, so a missing page fails the build instead
       * of quietly vanishing from the navigation. Only core/components is
       * autogenerated, because its pages are generated too.
       */
      sidebar: [
        {
          label: 'Get Started',
          items: [
            'get-started/changelog',
            'get-started/roadmap',
            'get-started/news',
            'get-started/versioning',
            'get-started/upgrading',
          ],
        },
        {
          label: 'Designing',
          items: ['designing/introduction'],
        },
        {
          label: 'Developing',
          items: ['developing/introduction', 'developing/react', 'developing/react-router'],
        },
        {
          label: 'Skills',
          items: ['skills/knowledge-skill'],
        },
        {
          label: 'Core',
          items: [
            { label: 'Components', items: [{ autogenerate: { directory: 'core/components' } }] },
            'core/tokens',
          ],
        },
        {
          label: 'Styling',
          items: ['styling/theming'],
        },
        {
          label: 'Help',
          items: ['help/faq', 'help/bug-report', 'help/feature-request', 'help/contributing', 'help/embedding'],
        },
      ],
      /*
       * Self-hosted Inter, never a CDN: the site's CSP sets font-src 'self'. The
       * token sheet defines the custom properties before reference.css maps
       * Starlight's variables onto them.
       */
      customCss: [
        '@fontsource/inter/400.css',
        '@fontsource/inter/500.css',
        '@fontsource/inter/600.css',
        './src/styles/tokens.generated.css',
        './src/styles/reference.css',
      ],
      lastUpdated: true,
    }),
  ],
});
