// Every collection and mode in tokens/manifest.json, resolved.
// Regenerated by `npm run build:token-data` — see build-token-data.js.

import core from '../../build/json/core.json';
import semanticColorLight from '../../build/json/semantic-color.light.json';
import semanticColorDark from '../../build/json/semantic-color.dark.json';
import spaceWeb from '../../build/json/semantic-space.web.json';
import spaceMobile from '../../build/json/semantic-space.mobile.json';
import spaceBackOffice from '../../build/json/semantic-space.back-office.json';
import typeWeb from '../../build/json/type.web.json';
import typeMobile from '../../build/json/type.mobile.json';
import typeBackOffice from '../../build/json/type.back-office.json';
import typographyStyles from '../../build/json/typography.styles.json';
import effects from '../../build/json/effects.styles.json';

export { core, semanticColorLight, semanticColorDark, typographyStyles, effects };

export const semanticColor = { light: semanticColorLight, dark: semanticColorDark };
export const space = { web: spaceWeb, mobile: spaceMobile, 'back-office': spaceBackOffice };
export const type = { web: typeWeb, mobile: typeMobile, 'back-office': typeBackOffice };

/** The three space/type modes, in the order the manifest lists them. */
export const MODES = ['web', 'mobile', 'back-office'];

export const byType = (tokens, t) => tokens.filter((x) => x.type === t);

/** Numeric-aware sort, so blue-50 lands before blue-600. */
const step = (name) => {
  const m = name.match(/(\d+)a?$/);
  return m ? Number(m[1]) : Number.POSITIVE_INFINITY;
};

/**
 * Group tokens into an ordered Map by a key function, preserving first-seen
 * key order — which is Figma's authored order, and the order a designer
 * expects to read them in.
 */
export const groupBy = (tokens, keyOf) => {
  const out = new Map();
  for (const t of tokens) {
    const k = keyOf(t);
    if (!out.has(k)) out.set(k, []);
    out.get(k).push(t);
  }
  return out;
};

/** `color-blue-600` -> `blue`, `color-neutral-900a` -> `neutral`. */
export const colorFamily = (t) => t.name.replace(/^color-/, '').replace(/-\d+a?$/, '');

/** `spacing-1` -> `spacing`, `border-radius-3` -> `border-radius`. */
export const dimensionFamily = (t) => t.name.replace(/-\d+$/, '');

/** `color-bg-primary-hovered` -> `bg`. */
export const semanticGroup = (t) => t.name.split('-')[1];

/** `spacing-padding-md` -> `spacing-padding`, `size-control-sm` -> `size-control`. */
export const spaceGroup = (t) => t.name.split('-').slice(0, -1).join('-');

export const sortByStep = (tokens) => [...tokens].sort((a, b) => step(a.name) - step(b.name));

/**
 * The type files store a scale as three parallel tokens per step
 * (size-/lineheight-/tracking-display-lg). Recombine them into one row so the
 * docs can show a real specimen instead of three orphaned numbers.
 */
export const typeScale = (tokens) => {
  const rows = new Map();
  for (const t of tokens) {
    const m = t.name.match(/^(size|lineheight|tracking)-(.+)$/);
    if (!m) continue;
    const [, part, stepName] = m;
    if (!rows.has(stepName)) rows.set(stepName, { step: stepName });
    rows.get(stepName)[part] = t;
  }
  // Only steps that carry a font size are a real scale step.
  return [...rows.values()].filter((r) => r.size);
};
